#!/usr/bin/env bash
# Validate a commit message against the agents-md commit rules.
#
# Usage:
#   scripts/lint-commit-msg.sh                # checks HEAD
#   scripts/lint-commit-msg.sh <file>         # checks message in <file>
#   scripts/lint-commit-msg.sh <ref1>..<ref2> # checks every commit in the range
#
# Exits 0 on pass, non-zero on any violation.

set -euo pipefail

JUNK_RE='^(update|fix|changes|wip|tmp|asdf|\.|test|new)$'
TYPE_RE='^(feat|fix|refactor|docs|chore|test|perf|build|ci|style|revert)(\([^)]+\))?!?: .+'

violations=0

check_one() {
  local subject="$1" sha="${2:-<input>}"
  local short
  short=$(printf '%s' "$subject" | head -1)

  if [ -z "$short" ]; then
    printf '✗ %s — empty commit subject\n' "$sha"
    violations=$((violations+1)); return
  fi

  if printf '%s' "$short" | grep -Eqi "$JUNK_RE"; then
    printf '✗ %s — banned message "%s"\n' "$sha" "$short"
    violations=$((violations+1)); return
  fi

  if ! printf '%s' "$short" | grep -Eq "$TYPE_RE"; then
    printf '✗ %s — does not match "type(scope)?: summary": %s\n' "$sha" "$short"
    violations=$((violations+1)); return
  fi

  if [ ${#short} -lt 10 ]; then
    printf '✗ %s — subject too short (%d chars): %s\n' "$sha" "${#short}" "$short"
    violations=$((violations+1)); return
  fi

  if [ ${#short} -gt 100 ]; then
    printf '✗ %s — subject too long (%d chars, max 100)\n' "$sha" "${#short}"
    violations=$((violations+1)); return
  fi

  printf '✓ %s — %s\n' "$sha" "$short"
}

arg="${1:-HEAD}"

if [ -f "$arg" ]; then
  msg=$(cat "$arg")
  check_one "$msg" "<file:$arg>"
elif printf '%s' "$arg" | grep -q '\.\.'; then
  # Skip merge commits — their subjects are auto-generated by Git/GitHub
  # (e.g. "Merge abc into def") and intentionally don't follow
  # Conventional Commits.
  while IFS= read -r line; do
    sha=$(printf '%s' "$line" | cut -d' ' -f1)
    subj=$(printf '%s' "$line" | cut -d' ' -f2-)
    check_one "$subj" "$sha"
  done < <(git log --no-merges --pretty=format:'%h %s' "$arg")
else
  subj=$(git log -1 --format='%s' "$arg")
  sha=$(git log -1 --format='%h' "$arg")
  check_one "$subj" "$sha"
fi

if [ "$violations" -gt 0 ]; then
  printf '\n%d violation(s). See docs/commits.md.\n' "$violations" >&2
  exit 1
fi
